### ISSUE TITLE
Enlarged images position error when page was zoomed

### ISSUE THREAD

**Issue by slikie** [afc163/MiniblogImgPop#2]
Just saw you updated :)
I'm huge fan of your work
But in zoomed pages(Chrome and Firefox usually zoomed at 120% and more)
pictures tend to be displayed in right side to the screen and are covered(limited) by screen
![untitled](https://cloud.githubusercontent.com/assets/13197246/13485872/dbe9f0ee-e146-11e5-86ba-714ce84a908a.png)

And I hope support over Douban can be added in new version
Simply by following codes will work fine with little bit of issues

```
'douban.com':{
    feedSelector:'img',
    sFrag       :'median',
    bFrag       :'raw'
},
```

**Comment by afc163** [comment]
Pull Request welcome~

**Comment by slikie** [comment]
I'm currently with zero CSS and Javascript knowledge and experience. Thus there are issues I have trouble fixing, eg. 1) longger picture won't apply with your beautiful swiping feature  2)by simple img selector some mixed pictures cannot be filtered, such as album and book covers. I was wondering if you would grant me this favor and enhance your wonderful script. I am aware that you're  being busy with your project and don't know if it's a lot to ask.
